#!/bin/sh -e
test $(which ssh-keygen) || \
    (echo "Can't find ssh-keygen. Is OpenSSH installed properly?"; exit 1)

usage () {
    echo "Usage: $0 init|newuser|newhost"
}

init () {
    echo Not implemented.
}

signuser () {
    echo Not implemented.
}

signhost () {
    echo Not implemented.
}

newhost () {
    echo Not implemented.
}

if [ $# -lt 1 ]
then
    usage
    exit 1
fi

case "$1" in
    init)
        init
        ;;
    signuser)
        signuser "$2"
        ;;
    signhost)
        signhost "$2"
        ;;
    newhost)
        newhost "$2"
        ;;
    *)
        usage
        exit 1
        ;;
esac
