#!/bin/sh -e
test $(which ssh-keygen) || \
    (echo "Can't find ssh-keygen. Is OpenSSH installed properly?"; exit 1)

usage () {
    echo "Usage: $0 init|newuser|newhost"
}

init () {
    echo Initializing new CA.
    mkdir -p hosts users
    ssh-keygen -qf CA -P "" -C ssh-ca
}

signuser () {
    echo "Signing user $1 key."
    ssh-keygen -s CA -I "$1" -n "$1" "users/$1.pub"
}

signhost () {
    echo "Signing host $1 key."
    ssh-keygen -s CA -I "$1" -h -n "$1" "hosts/$1.pub"
}

newhost () {
    echo "Creating new host $1 keypair."
    ssh-keygen -qf "hosts/$1" -P "" -C "$1"
    signhost "$1"
}

newuser () {
    echo "Creating new user $1 keypair."
    ssh-keygen -qf "users/$1" -P "" -C "$1"
    signuser "$1"
}

if [ $# -lt 1 ]
then
    usage
    exit 1
fi

case "$1" in
    init)
        init
        ;;
    signuser)
        signuser "$2"
        ;;
    signhost)
        signhost "$2"
        ;;
    newhost)
        newhost "$2"
        ;;
    newuser)
        newuser "$2"
        ;;
    *)
        usage
        exit 1
        ;;
esac
